# Generated by Django 5.0.2 on 2024-09-10 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 12, 11, 55, 997403, tzinfo=datetime.timezone.utc)),
        ),
    ]
